all:
	- cd purger && make
	- cd util && make

clean:
	- cd purger && make clean
	- cd util && make clean
	- rm -f *~

distclean:
	- cd purger && make distclean
	- cd util && make distclean
	- rm -f *~
