all:
	- cd common && make
	- cd prm && make
	- cd treewalk && make

clean:
	- cd common && make clean
	- cd prm && make clean
	- cd treewalk && make clean
	- rm -f *~

distclean:
	- cd common && make distclean
	- cd prm && make distclean
	- cd treewalk && make distclean
	- rm -f *~
