.TH "reaper" "1" "purger 0.0.1" "September 2011" "Purger Tools"

.SH "NAME"
reaper \- Remove old files after being located by treewalk.

.SH "SYNOPSIS"
\fBreaper\fR            [\fIOPTIONS\fR...]

.SH "DESCRIPTION"
This is a program that reads the results of treewalk and deletes old files.
.br
http://github.com/hpc/purger

.SH "OPTIONS"
.LP

.TP
\fB\-?\fR
Display help information and exit.

.SH "SEE ALSO"
\fBtreewalk\fR(1)
