.TH "treewalk" "1" "purger 0.0.1" "September 2011" "Purger Tools"

.SH "NAME"
treewalk \- Distribute file stats across nodes in a compute cluster

.SH "SYNOPSIS"
\fBtreewalk\fR            [\fIOPTIONS\fR...]

.SH "DESCRIPTION"
This is a program that performs a distributed stat() using libcircle. The
results are then stored in a database.
.br
http://github.com/hpc/purger

.SH "OPTIONS"
.LP

.TP
\fB\-?\fR
Display help information and exit.

.SH "SEE ALSO"
\fBreaper\fR(1)
